[package]
name = "sha1"
description = "SHA-1 hash function"
version = "0.1.0"
cairo-version = "2.7.0"
edition = "2024_07"
repository = "https://github.com/j1mbo64/sha1_cairo"
keywords = ["hash", "crypto"]

[dev-dependencies]
cairo_test = "2.7.0"
