name: cairo

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all

inputs:
  tool_versions: scarb 2.7.0

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "scarb 2.7.0" > .tool-versions
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v3
      - run: scarb fmt --check
      - run: scarb build
      - run: scarb test
